# config/config.yaml

orm:
  default:
    # ✅ localhost use করো (mysql → localhost)
    mysql: root:password@tcp(localhost:3306)/hitrix_test?charset=utf8mb4&parseTime=True
    
    # ✅ localhost use করো (redis → localhost)
    redis: localhost:6379:1
    
    locker: default
    local_cache: 1000

authentication:
  secret: "a-deep-dark-secret"
  support_otp: true
  otp_length: 5

server:
  port: 8080

cors:
  - http://localhost:9001
  - http://localhost:63342